disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- line_length
- multiple_closures_with_trailing_closure

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
